package com.walmartlabs.productgenome.rulegenerator.service;

import java.util.List;
import java.util.Map;

import com.google.common.collect.Lists;
import com.walmartlabs.productgenome.rulegenerator.model.Simmetrics;
import com.walmartlabs.productgenome.rulegenerator.model.data.Dataset;
import com.walmartlabs.productgenome.rulegenerator.model.data.Feature;
import com.walmartlabs.productgenome.rulegenerator.model.data.FeatureDataset;
import com.walmartlabs.productgenome.rulegenerator.model.data.FeatureVector;
import com.walmartlabs.productgenome.rulegenerator.model.data.ItemPair;
import com.walmartlabs.productgenome.rulegenerator.utils.SimilarityUtils;

/**
 * Generates new similarity features from the raw dataset.
 * 
 * @author excelsior
 *
 */
public class FeatureGenerationService {

	/**
	 * Generates the new feature based dataset using the raw dataset.
	 * 
	 * The new features are generated by multiplexing raw attributes with
	 * relevant similarity metrics, to generate apt features.
	 * 
	 * @param rawDataset
	 * @return
	 */
	public FeatureDataset generateFeatures(Dataset rawDataset)
	{
		String name = rawDataset.getName();
		Map<String, List<Simmetrics>> attrSimmetrics = 
				AttributeSimmetricsRecommender.getSimmetricRecommendations(rawDataset);

		List<Feature> features = getAllFeatures(attrSimmetrics);
		List<ItemPair> itemPairs = rawDataset.getItemPairs();
		List<FeatureVector> featureVectors = Lists.newArrayList();		
		for(ItemPair itemPair : itemPairs) {
			FeatureVector fVector = getFeatureVector(itemPair, features);
			featureVectors.add(fVector);
		}

		return new FeatureDataset(name, features, featureVectors);
	}
	
	/**
	 * Generates all features for the attributes in the current dataset using the
	 * recommended similarity metrics.
	 * @param attrSimmetrics
	 * @return	List of features
	 */
	private static List<Feature> getAllFeatures(Map<String, List<Simmetrics>> attrSimmetrics)
	{
		List<Feature> features = Lists.newArrayList();
		for(Map.Entry<String, List<Simmetrics>> entry : attrSimmetrics.entrySet()) {
			String attrName = entry.getKey().toLowerCase();
			for(Simmetrics metric : entry.getValue()) {
				features.add(new Feature(attrName, metric));
			}
		}
		
		return features;
	}
	
	/**
	 * Generates a feature vector, corresponding to the raw itempair.
	 * 
	 * Each feature is an application of a similarity metric on an attribute and the
	 * value represents the similarity score.
	 * @param itemPair
	 * @param features
	 * @return
	 */
	private static FeatureVector getFeatureVector(ItemPair itemPair, List<Feature> features)
	{
		List<Double> featureValues = Lists.newArrayList();
		for(Feature f: features) {
			String attrName = f.getAttrName();
			Simmetrics metric = f.getSimMetric();
			
			String itemAVal = itemPair.getItemAValByAttr(attrName);
			String itemBVal = itemPair.getItemBValByAttr(attrName);
			double score = SimilarityUtils.getSimilarity(metric, itemAVal, itemBVal);
			
			featureValues.add(score);
		}
		
		return new FeatureVector(featureValues, itemPair.getMatchStatus());
	}
}
